name: shturk

on:
  schedule:
    - cron: '0 */3 * * *' # Her 3 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests certifi

      - name: Install requests module
        run: python3 -m pip install requests

      - name: Execute Python script
        run: python3 shturk.py > streams/shturk.m3u8

      - name: commit & push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "shturk updated $(date +'%Y-%m-%d %H:%M:%S') [skip ci]" || echo "No updated streams"
          git push
